export const FETCH_DATA_START_SAGA = 'FETCH_DATA_START_SAGA';
export const FETCH_DATA_SUCCESS_SAGA = 'FETCH_DATA_SUCCESS_SAGA';
export const FETCH_DATA_FAIL_SAGA = 'FETCH_DATA_FAIL_SAGA';
export const FETCH_DATA_SAGA = 'FETCH_DATA_SAGA';